# Generated by Django 2.2 on 2020-05-03 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(verbose_name='date published')),
                ('source', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=350)),
                ('current_stage', models.CharField(max_length=30)),
            ],
        ),
    ]
