# Generated by Django 2.2 on 2020-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='creation_time',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date_followed', models.DateTimeField(auto_now=True)),
                ('lead_name', models.ForeignKey(on_delete='DO_NOTHING', to='leads.Lead')),
            ],
        ),
    ]
