# Generated by Django 2.2 on 2020-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200504_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_followed',
            field=models.DateTimeField(verbose_name='date followed'),
        ),
    ]
