# Generated by Django 2.2 on 2020-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200504_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='medium_used',
            field=models.CharField(choices=[('call', 'CALL'), ('whatsapp', 'WHATSAPP'), ('email', 'EMAIL')], default='call', max_length=10),
        ),
    ]
